name: CI SNAPSHOT

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_snapshot:
    uses: ./.github/workflows/spring-artifactory-maven-snapshot.yml
    with:
      mavenArgs: '-Pdocs,spring -U'
    secrets: inherit